typescript
export const SEISMIC_CONSTANTS = {
  // Earth parameters
  EARTH_RADIUS_KM: 6371,
  EARTH_GRAVITY_MS2: 9.80665,
  
  // Seismic wave velocities
  P_WAVE_VELOCITY_MIN_KMS: 5.5,
  P_WAVE_VELOCITY_MAX_KMS: 13.7,
  S_WAVE_VELOCITY_MIN_KMS: 3.0,
  S_WAVE_VELOCITY_MAX_KMS: 7.2,
  
  // Temperature thresholds
  MANTLE_TEMPERATURE_THRESHOLD_CELSIUS: 1500,
  CORE_TEMPERATURE_THRESHOLD_CELSIUS: 5000,
  CRUST_TEMPERATURE_THRESHOLD_CELSIUS: 1000,
  
  // Pressure factors
  PRESSURE_FACTOR_DEEP_CRUST: 1.5,
  PRESSURE_FACTOR_MANTLE: 2.0,
  PRESSURE_FACTOR_CORE: 3.0,
  
  // Depth ranges
  SHALLOW_FOCUS_DEPTH_KM: 70,
  INTERMEDIATE_FOCUS_DEPTH_KM: 300,
  DEEP_FOCUS_DEPTH_KM: 700,
  
  // Magnitude thresholds
  ANOMALOUS_MAGNITUDE_THRESHOLD: 7.0,
  SUPERSEISMIC_MAGNITUDE_THRESHOLD: 8.0,
  
  // Rupture velocity limits
  MAX_RUPTURE_VELOCITY_KMS: 3.5,
  MIN_RUPTURE_VELOCITY_KMS: 1.0,
  
  // Thermal gradient thresholds
  NORMAL_THERMAL_GRADIENT_CELSIUS_PER_KM: 25,
  ANOMALOUS_THERMAL_GRADIENT_CELSIUS_PER_KM: 40,
  
  // Rock composition densities (g/cm³)
  ROCK_DENSITY_BASALT: 3.0,
  ROCK_DENSITY_ANDESITE: 2.7,
  ROCK_DENSITY_GRANITE: 2.65,
  ROCK_DENSITY_LIMESTONE: 2.7,
  
  // Fault behavior indicators
  FAULT_STRESS_THRESHOLD: 100, // MPa
  RAPID_STRESS_RELEASE_THRESHOLD: 50, // MPa
  UNUSUAL_RUPTURE_VELOCITY_RATIO: 0.8,
  
  // Time-based parameters
  MIN_DURATION_SECONDS: 10,
  MAX_DURATION_SECONDS: 300,
  WARNING_DURATION_SECONDS: 60,
  
  // Statistical thresholds
  SIGMA_THRESHOLD_HIGH: 2.5,
  SIGMA_THRESHOLD_LOW: 1.5,
  
  // Data processing constants
  SAMPLE_RATE_HZ: 100,
  WINDOW_SIZE_SAMPLES: 1024,
  FILTER_CUTOFF_FREQUENCY_HZ: 10,
  
  // Anomaly detection thresholds
  TEMPERATURE_PRESSURE_ANOMALY_THRESHOLD: 0.8,
  STRESS_PROPAGATION_ANOMALY_THRESHOLD: 0.7,
  RUPTURE_PATTERN_ANOMALY_THRESHOLD: 0.6,
  
  // Geological layer boundaries
  CRUST_BOUNDARY_KM: 35,
  MANTLE_BOUNDARY_KM: 660,
  OUTER_CORE_BOUNDARY_KM: 3480,
  INNER_CORE_BOUNDARY_KM: 5150,
  
  // Seismic zone classifications
  SEISMIC_ZONE_HIGH_RISK: 'high_risk',
  SEISMIC_ZONE_MEDIUM_RISK: 'medium_risk',
  SEISMIC_ZONE_LOW_RISK: 'low_risk',
  SEISMIC_ZONE_UNKNOWN: 'unknown'
} as const;